-- AlterTable
ALTER TABLE "Job" ADD COLUMN "computeCostUsd" REAL;
ALTER TABLE "Job" ADD COLUMN "o2Cost" REAL;
ALTER TABLE "Job" ADD COLUMN "o2Refund" REAL;
ALTER TABLE "Job" ADD COLUMN "platformFeeUsd" REAL;
ALTER TABLE "Job" ADD COLUMN "tokensIn" INTEGER;
ALTER TABLE "Job" ADD COLUMN "tokensOut" INTEGER;
